name: Update Contract Addresses

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  refresh_contract_addresses:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Update Files
      id: update
      run: |
        pip3 install -r .github/python_actions/requirements.txt
        python3 .github/python_actions/genContractLists.py
        git add -A

    - name: pull-request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "Scheduled update from changes to monorepo"
        title: "Scheduled update from changes to monorepo"
        branch: gha-contract-addresses
        reviewers: "Tritum-VLK"
        assignees: "Tritum-VLK"
        labels: "Automatic"
